# Server configuration
server.port=8081

# PostgreSQL database configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d7t38ajeo5us73f1algg-a.ohio-postgres.render.com:5432/db_bazar_fj8f}
spring.datasource.username=${DB_USER:bazar_user}
spring.datasource.password=${DB_PASSWORD:uRLp7QVL8mIdiYn8tjKBG1AAlhnBzEZ5}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
