spring.datasource.url=jdbc:postgresql://localhost:5432/bazar_db
spring.datasource.username=bazar_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB
cloudinary.cloud-name=bazarcito
cloudinary.api-key=755229573469928
cloudinary.api-secret=RmFtLuS1bBshyOAFSLK9d1vOHCQ
app.seed-demo-data=false